cpp-best-practices/cppbestpractices

03-Style.md
Awesome book! Thank you for making this available.
=> Miscellaneous spelling

07-Considering_Performance.md
I would suggest to take this into the best practices.
Thanks for this great document!
=> If possible prefer unique_ptr to shared_ptr because it is more efficient

04-Considering_Safety.md
One more example of using unique_ptr
=> Add buffer example for unique_ptr

08-Considering_Performance.md
Improved recommendation to use pre-increment in loops instead of post-increment (see issue #19).
I think this will clarify this. Feel free to improve my English, i am no native speaker :)
=> Improvement for ++i vs i++

02-Use_the_Tools_Available.md
Changed the URL of include what you use from code.google.com to Github as per recommendation from include what you use
=> Changed of external url

03-Style.md
Added some thoughts and some high ranked (and good) links to web
resources
=> Filled out "Use Operator Overloads Judiciously"

02-Use_the_Tools_Available.md
Added some links, fixed some typos etc.
=> Several minor improvements

02-Use_the_Tools_Available.md
Add a other tools section and move Metrix++ entry there.
Also add ABI compliance checker to other tools section.
=> Add other tools section (#33)

02-Use_the_Tools_Available.md
@PeterSommerlad asked me to update the entry on Cevelop.
=> Update entry on Cevelop

02-Use_the_Tools_Available.md
[CppUTest](https://github.com/cpputest/cpputest) added to Test Libraries. It's much like Google Test, but with an additional focus on embedded systems.
- Very handy for C++ – especially in an embedded area
- Mock Support included
- Memleak detection
- Documentation<sup>*)</sup>
--------------------------------
<sup>*)</sup> This includes books, eg. _Modern C++ Programming with Test-Driven Development_.
=> CppUTest added to Test Libraries

02-Use_the_Tools_Available.md
Gitlab description updated (source: https://about.gitlab.com/gitlab-com/)
=> Gitlab description updated

02-Use_the_Tools_Available.md
Exactly what it says in the title. There are other sanitizers, but they are not one of the big ones (ie stack sanitizer).
=> MSan should also be mentioned amongst sanitizers.

02-Use_the_Tools_Available.md
Hello! We develop a static code analyzer PVS-Studio for C/C++ and C#. Recently we have added a possibility to use the analyzer for free for several types of projects. It would be great if you include our analyzer in this list.
=> Add PVS-Studio static analyzer.

08-Considering_Performance.md
Add missing semicolon to std::bind example
=> fix missing semicolon

08-Considering_Performance.md
moved from code.google.com to github
=> Update include-what-you-use url

03-Style.md
If possible, mark member variables 'const'.
=> const member variable

03-Style.md
Dead link to rule of zero article fixed.
=> Link to rule of zero article fixed

02-Use_the_Tools_Available.md
I'd like to share my experience, but I'm not sure is it related for your book. So feel free to reject my pull-request.
=> Added suggestions for usage of cppcheck

02-Use_the_Tools_Available.md
In my opinion GitLab is very useful tool. Due to support of custom Docker images it is very flexible for any CI issues.
=> Add GitLab to CI section.

09-Enable_Scripting.md
- Add links to existing examples of scripting options
- Explain what SWIG is
- Add pybind11 as an example
=> Updating scripting page

02-Use_the_Tools_Available.md
Hi Jason, I enjoy OCLint a lot and put it in all my `.travis.yml` files ([here is an example](https://github.com/richelbilderbeek/travis_qmake_gcc_cpp14_oclint)), so others may appreciate it as well. Cheers, Richel
=> Added OCLint

10-Further_Reading.md
I found this to be an excellent guide for modern cmake. I don't know who is behind it,
I found out from a tweet by Martin Moene.
=> Add reference for cmake

02-Use_the_Tools_Available.md
GitHub now provides free private repositories as well (for up to 3 collaborators).
=> updated GitHub description (providing free private repos)

03-Style.md
=> rmf.io is dead

02-Use_the_Tools_Available.md
Add Microsoft's `vcpkg` package manager.
=> Add vcpkg to 'Use the Tools Available'

09-Considering_Correctness.md
Also a worthy strong type library to consider IMHO
=> Add Jonathan Boccara's NamedType library

02-Use_the_Tools_Available.md
This PR also removes a lot of trailing whitespace from the same file.
=> Add pahole to the list of other tools

02-Use_the_Tools_Available.md
=> fix: fix link to Memoro

README.md
=> Fixed broken youtube link in README.md

08-Considering_Performance.md
This updates the list of profilers.
=> Update the list of profilers

02-Use_the_Tools_Available.md
Hi, I found there is another `Heap profiling` in the same file, which also contains `Memoro`, please refer to the following photo
=> Remove duplicated content

04-Considering_Safety.md
The main fix is changing "by" to "of", but I made a few other changes that might be more clear.
=> Considering_Safety typo fix
