cpp-best-practices/cppbestpractices

- 07-Considering_Performance.md
> Typo with Initializer Lists

- 04-Considering_Safety.md
Another suggestion from me:
Use the C++-style cast(static\_cast<>, dynamic\_cast<> ...) instead of the C-style cast. The C++-style cast allows more compiler checks and is considerable safer.
> Prefer C++-style cast

- 02-Use_the_Tools_Available.md
I replaced the version specific link with a generic link that will always redirect to the newest version of Boost.Test
> Replaced a version specific link to Boost.Test

- 07-Considering_Threadability.md
I would suggest to add the M&M rule (c++11) to Threadability:
Mutex and mutable go together
For more information to this rule see the blog from Herb Sutter:
http://herbsutter.com/2013/05/24/gotw-6a-const-correctness-part-1-3/
> Suggestion: Adding M&M rule to Threadability

- 02-Use_the_Tools_Available.md
Jenkins is a fork of Hudson that was released in 2011. At the moment Jenkins seems to be significantly more used than Hudson.
> Continuous Integration: If you mention Hudson you should mention Jenkins too

- 02-Use_the_Tools_Available.md
The --enable parameter to cppcheck is called -enable here.
> Fix --enable=all parameter to cppcheck

- 03-Style.md
- 04-Considering_Safety.md
- 05-Considering_Maintainability.md
- 07-Considering_Threadability.md
- 10-Further_Reading.md
Fixed some typos, added some links and further minor improvements
> Minor improvements

- 08-Considering_Performance.md
I started to fill the section about precompiled headers with some general information and some links to manuals for the common compiler. Any additional suggestions?
> Precompiled Header

- 10-Further_Reading.md
There is a really good new C++ Core Guideline from Bjarne Stroustrup and Herb Sutter.
> Added link to C++ Core Guideline

- 03-Style.md
I added a few missing punctuations and cleaned up the wording in a few places to
make it a little clearer.
I fixed the name of the constructor in a couple of the code examples.
> Edit style section for grammar and clarity

- 04-Considering_Safety.md
I would suggest to add some information to variadic functions because the usage could be a great security risk.
What do you think about this? Do we need some examples or further information about this?
> Do not define a variadic function

- 03-Style.md
The content has moved to a new site and the currently linked version has code formatting issues.
> Updated a link to new site

- 02-Use_the_Tools_Available.md
Google Test was moved from code.google.com to github.
> Updated URL for Google Test

- 03-Style.md
Clarifying that narrowing is allowed with `=` but not with `{ }`.
> Clarify narrowing between = and {}

- 03-Style.md
I think the distinction here is important. There is no performance gain for POD types and we should be explicit about that 😄
> Clarifying performance in POD vs other in initializer lists.

- 05-Considering_Maintainability.md
Prior to C++11, only static const data members of
integral or enumeration type could have initializers
in the class definition. C++11 extends that to
floating point types (float, double) as well.
However, in order for such members to be initialized
in the class defintion, such members must either be
constexpr or non-static.
> static constant floating point use constexpr

- 02-Use_the_Tools_Available.md
In the "MSVC" section, "/w14640" is correctly given as lowercase in the detailed list, but wrongly given with uppercase "W" in the summary above.
> /W14640 => /w14640

- 02-Use_the_Tools_Available.md
Added a note like (only in GCC >= 4.8) or (GCC >= 4.6, Clang >= 3.8) for every suggested -Wxxx flag since they are not uniformly supported. Based on WARN_FLAGS setup code in https://github.com/ashutosh108/sb-sloka-counter/blob/d209af97b567e4e92ed8ca7500e34c759a860885/CMakeLists.txt. Verified by using godbolt.org and digging around release notes.
> add GCC/Clang compiler versions for warning flags

- 02-Use_the_Tools_Available.md
The correct arg has a capital X `/WX`. `/Wx` is treated like `/W<number>` but fails the parsing and generates an invalid number (I suppose).
> /Wx raises Command-Line Error D8021

- 02-Use_the_Tools_Available.md
Added a description for `-pedantic` and clarified similarly to the MSVC section
> Clarify GCC/Clang compiler flags

- 02-Use_the_Tools_Available.md
`build2` is a toolchain with both build-system and package manager (and a few other tools to help project management). This adds it to the build system list (it can be used with only the build system) and clarifies that it's a complete toolchain in both references.
> Fixed slightly incorrect build2 references

- 00-Table_of_Contents.md
- 02-Use_the_Tools_Available.md
- 03-Style.md
- 04-Considering_Safety.md
- 05-Considering_Maintainability.md
- 08-Considering_Performance.md
- 09-Considering_Correctness.md
- 11-Further_Reading.md
- 12-Final_Thoughts.md
- LICENSE
- SUMMARY.md
I was looking through the source files here and noticed there were some lines with trailing whitespace and some files with extra newlines at the end, so I figured I'd strip it out and open a PR.
> Remove trailing whitespace

- 02-Use_the_Tools_Available.md
This is a really good way to temporarily develop with `/Wall` enabled, then switching back to `/W4` after fixing all of the extra warnings.
You can also disable other types of diagnostics in STL headers, e.g. `/external:templates-`, `/analyze:external-`.
> Add note about VS2022's treat angle brackets as external feature

- 09-Considering_Correctness.md
Github does not render link if it contains bare spaces. URL-encoding them fixes the issue.
> Fix link to PDF in "Considering Correctness"

- 04-Considering_Safety.md
The original link to Kotaku results in `ERR_TOO_MANY_REDIRECTS`, this change links to the original 2013 article using a Wayback machine link.  I'd have used the updated link, but most of the links to the article's images are broken.
> Fix broken link to John Carmack's comments on `const`
